### ISSUE TITLE
Add Warning output for values with leading or trailing whitespace

### ISSUE THREAD

**Issue by mattywausb** [jlolling/talendcomp_tContextInput#2]
Some configuration parameters treat leading or trailing whitespace characters as relevant content. (e.g. Username or password in DB connection). Since in normal cases the wanted value has no leading/trailing whitespace, an unintended input with whitespace in the propertyfile, will lead to a configuration error, that is very hard to see.  I suggest that the component writes out a warning log message for all property values, where it detects a leading or trailing whitespace. It should not modify the value, because sometimes it might be intended.

**Comment by jlolling** [comment]
This is not possible. The component uses the standard API for loading
properties and here keys and values will always be trimmed. It's a very
dangerous behaviour to add a whitespace at the beginning or end of any
value in configuration properties.

Matthias Wegner <notifications@github.com> schrieb am Fr., 24. Juli 2020,
11:03:

**Comment by mattywausb** [comment]
" It's a very dangerous behaviour to add a whitespace at the beginning or end of any
value in configuration properties." - Thats true, but nevertheless it happened and took us alot of effort to track down. So the standard API seems not to trim the data perfectly. The code of the component just has to check the final loaded content for leading/trailing whitespace. Probably with a regex or by trimming it with a reliable function and comparing its cleansed string with the loaded one.

**Comment by jlolling** [comment]
We can cope with leading or trailing whitespaces by enclosing such values in double quotas.
But using whitespaces before or after the = as relevant content is actually a nightmare and we should not consider taking care of them.
A warning is not an option because who is taking care of it?
The possibility of making mistakes is very high!

Or we switch to another format like yaml. This format is like json and here we can have leading/trailing whitespaces in values.
